# Generated by Django 5.1.6 on 2025-02-27 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_options_task_id_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='id_task',
        ),
    ]
